# Generated by Django 4.0.4 on 2022-06-15 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='project',
            new_name='project_id',
        ),
    ]
