# Generated by Django 4.0.4 on 2022-06-15 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_rename_project_rating_project_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='project_id',
            new_name='project',
        ),
    ]
