# Generated by Django 4.0.4 on 2022-06-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0012_alter_rating_project_alter_rating_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='average',
        ),
        migrations.AddField(
            model_name='rating',
            name='content_average',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='design_average',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='score',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='usability_average',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
